version: '3'
services:
    database:
        build: ./database
        restart: always
        container_name: database
        volumes:
            - ./database/scrip/:/docker-entrypoint-initdb.d
            - ./database/scrip/mysql-data:/var/lib/mysql
    backend:
        build: ./backend
        restart: always
        container_name: backend
        volumes: 
            - ./backend/public/images:/public/images
        depends_on: 
            - database
    frontend:
        build: ./frontend
        restart: always
        container_name: frontend
        depends_on: 
            - database
            - backend
    reverseproxy:
        image: nginx
        restart: always
        container_name: reverseproxy
        volumes: 
            - ./reverseproxy/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - database
            - backend
            - frontend
        ports:
            - "80:80"

networks:
    default:
        external:
            name: skorproductnetwork
