version: '3'
services:
    database:
        build: ./database
        restart: always
        container_name: database
        environment: 
           -MYSQL_USER: ${MYSQL_USER}
           -MYSQL_DATABASE: ${MYSQL_DATABASE}
           -MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - ./database/scrip/:/docker-entrypoint-initdb.d
            - ./database/scrip/mysql-data:/var/lib/mysql
    backend:
        build: ./backend
        restart: always
        container_name: backeend
        volumes: 
            - ./backend/public/images:/public/images
        depends_on: 
            - database
    frontend:
        build: ./frontend
        restart: always
        container_name: frontend
        depends_on: 
            - database
            - backend
    proxy:
        image: nginx
        restart: always
        container_name: proxy
        volumes: 
            - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - database
            - backend
            - frontend
        ports:
            - "80:80"

networks:
    default:
        external:
            name: skorproductnetwork
