version: '3'
services:
    db:
        build: ./database
        restart: always
        container_name: db
        volumes:
            - ./database/scrip/:/docker-entrypoint-initdb.d
            - ./database/scrip/mysql-data:/var/lib/mysql
    be:
        build: ./backend
        restart: always
        container_name: be
        volumes: 
            - ./backend/public/images:/public/images
        depends_on: 
            - db
    fe:
        build: ./frontend
        restart: always
        container_name: fe
        depends_on: 
            - db
            - be
    proxy:
        image: nginx
        restart: always
        container_name: proxy
        volumes: 
            - ./reverseproxy/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - db
            - be
            - fe
        ports:
            - "80:80"

networks:
    default:
        external:
            name: skorproductnetwork
